/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package hidenseek.test.entity;

import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertTrue;

import java.util.Set;

import org.junit.jupiter.api.Test;

import hidenseek.model.components.Component;
import hidenseek.model.components.InputHandlerComponent;
import hidenseek.model.components.LifeComponent;
import hidenseek.model.components.LifeComponentImpl;
import hidenseek.model.components.LinearMovementComponentImpl;
import hidenseek.model.components.MoveComponent;
import hidenseek.model.entities.Entity;
import hidenseek.model.entities.AbstractEntity;

public class EntityTest {
    @Test public void testEntityComponents() {
        Entity e = new AbstractEntity() {};
        assertTrue(e.getComponent(LifeComponent.class).isEmpty());
        e.attach(new LifeComponentImpl(100));
        assertFalse(e.getComponent(LifeComponent.class).isEmpty());
        e.detach(LifeComponent.class);
        assertTrue(e.getComponents().isEmpty());
        
        e.attach(new LifeComponentImpl(100));
        e.attach(new LinearMovementComponentImpl());  
        e.detach(LifeComponent.class);
        Set<Component> components = e.getComponents();
        assertTrue(components.size() == 1);
        assertTrue(MoveComponent.class.isInstance(components.stream().findFirst().get()));
        assertTrue(e == e.getComponent(MoveComponent.class).get().getOwner().get());
    }
    
    @Test public void testLifeComponent() {
        LifeComponent l = new LifeComponentImpl(100);
        assertTrue(l.getMaxHealth() == 100);
        l.hurt(10);
        assertTrue(l.getHealth() == 90);
        l.hurt(100);
        assertTrue(l.getHealth() == 0);
        
    }
    
    @Test public void testInputHandlerComponent() {
        InputHandlerComponent input;
        //input.mapKeyToAction(KeyCode.A, (entity) -> entity.getComponent(MoveComponent.class).ifPresent(c -> c.move()));
    }
}
