/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package hidenseek.test.entity;

import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertTrue;

import org.junit.jupiter.api.Test;

import hidenseek.model.Entity;
import hidenseek.model.EntityImpl;
import hidenseek.model.components.LifeComponent;
import hidenseek.model.components.LifeComponentImpl;

public class EntityTest {
    @Test public void testEntityComponents() {
        Entity e = new EntityImpl();
        
        assertTrue(e.getComponent(LifeComponent.class).isEmpty());
        
        e.attach(new LifeComponentImpl(100));
        
        assertFalse(e.getComponent(LifeComponent.class).isEmpty());
        
        e.detach(LifeComponent.class);
        
        assertTrue(e.getComponents().isEmpty());
    }
    
    @Test public void testLifeComponent() {
        LifeComponent l = new LifeComponentImpl(100);
        
        assertTrue(l.getMaxHealth() == 100);
        
        l.hurt(10);
        
        assertTrue(l.getHealth() == 90);
        
        l.hurt(100);
        
        assertTrue(l.getHealth() == 0);
        
    }
}
